######################################################################
##
## Filename: Sin_t_tb.udo
## Created on: Fri Jun 09 9:25:16 AM Iran Daylight Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
